language: python
python:
- 3.7.5
install:
- pip install pipenv
- pipenv install --dev
script:
- pipenv run coverage run --source=app -m unittest
after_success:
- pipenv run coveralls
deploy:
  provider: heroku
  api_key:
    secure: p7lC3fKRqHfJUCi8kRtrNkXtX5r4LWBkn8nyqVwCrmC8qAdsn8eewZLRB1E6+sSgfkYd5LE+IDMdz5hnlVPj6AYE5lsPt4Efi8Gq7mUUU8ruyNAfR0fQ3ffqfNUfqXYmOaJ//M12jNn7FW0Ga0y5T1etdVL8PaDZbPjWE6UhJXzsYhUuSqjtyF3kikj5x0XU7MlQOyiwbK4tMLCEwH3bDq8jVt2JHAJXfXFnscJ2Q8C5iRu81C9Iqut7SwzKd+o0p3cECbeNEm4bOZ+J/ExoaAPjQrIzBr8Egxo9/knMCZBmepHrKGOefKHzKcgID1O2ctFQ2eL/OjEwEGWAjz3zS1hl8xd7osI2TABLRzW2d3nH7PKq81o3QSEI1moVo8UQUsYK6n39Fx1mnRhmIBKWwA/QU+j9Ehxr1FRpY4E0E8HO6VdRTYq34T/uYSMvY4HzXaz+UhPMCx1YK3fpwlo1qsV+xF0MDKnBIy+XbJ+/JI6Ok+3HXl/ygjvpZu3L95bB8BJUX6DTrvQpHca67wlQELhp/bVysxseX4ll6ua9rAPMv5jiKi9tZBRj0OOJXNyp/AfYpgLNAvdDBgRE/4RQMAWQIrdCUQzrNXmaWTpM94xP4Ffa5gwjZMktsKLUvorKu5ixq9d8hjyTUIFvcL3K18YpAO9sSHB02FkBLZp1TY4=
    run: "python manage.py db upgrade"
  app: anto-playground
