"""add todo table

Revision ID: c31a1f45ba8e
Revises: bf99f9a0a9c3
Create Date: 2019-12-08 11:59:34.987367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c31a1f45ba8e"
down_revision = "bf99f9a0a9c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todo",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("todo_id", sa.String(length=100), nullable=True),
        sa.Column("task_description", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_edited_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        # sa.UniqueConstraint("task_description"),
        sa.UniqueConstraint("todo_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("todo")
    # ### end Alembic commands ###
